# Generated by Django 5.0 on 2023-12-11 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('color', models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Gray', 'Gray'), ('Brown', 'Brown'), ('Orange', 'Orange'), ('Mixed', 'Mixed')], max_length=20)),
                ('is_adopted', models.BooleanField(default=False)),
                ('adoption_status', models.CharField(choices=[('Soon', 'Available Soon'), ('Now', 'Available Now'), ('Unavailable', 'Not Available'), ('Pending', 'Adoption Pending')], default='Soon', max_length=15)),
                ('spayed_neutered', models.BooleanField(default=False)),
                ('intake_date', models.DateField(default='2023-12-11')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopter_name', models.CharField(max_length=100)),
                ('adoption_date', models.DateField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=10)),
                ('is_home_approved', models.BooleanField(default=False)),
                ('adoption_fee_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('adoption_complete', models.BooleanField(default=False)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.cat')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('description', models.TextField(max_length=200)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='management.cat')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='health_records',
            field=models.ManyToManyField(blank=True, related_name='cats_health_records', to='management.healthrecord'),
        ),
        migrations.CreateModel(
            name='SpayNeuterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_date', models.DateField()),
                ('veterinarian_name', models.CharField(max_length=100)),
                ('clinic_name', models.CharField(max_length=150)),
                ('clinic_street_address', models.CharField(max_length=255)),
                ('clinic_city', models.CharField(max_length=100)),
                ('clinic_state', models.CharField(max_length=2)),
                ('clinic_postal_code', models.CharField(max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.cat')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(choices=[('FVRCP', 'FVRCP'), ('Rabies', 'Rabies'), ('FeLV', 'FeLV')], max_length=10)),
                ('administration_date', models.DateField()),
                ('administering_vet', models.CharField(max_length=100)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination', to='management.cat')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='vaccinations',
            field=models.ManyToManyField(blank=True, related_name='cats_vaccinated', to='management.vaccinationrecord'),
        ),
    ]
