# Generated by Django 5.0 on 2023-12-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='intake_date',
            field=models.DateField(default='2023-12-12'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
