# Generated by Django 5.0 on 2023-12-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_cat_intake_date_alter_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='adoption_status',
            field=models.CharField(choices=[('Available Soon', 'Available Soon'), ('Available Now', 'Available Now'), ('Unavailable', 'Not Available'), ('Adoption Pending', 'Adoption Pending'), ('Adopted', 'Adopted')], default='Soon', max_length=16),
        ),
        migrations.AlterField(
            model_name='cat',
            name='intake_date',
            field=models.DateField(default='2023-12-13'),
        ),
    ]
