# Generated by Django 5.0 on 2023-12-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
