# Generated by Django 5.0 on 2023-12-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_delete_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='is_adopted',
        ),
        migrations.AlterField(
            model_name='cat',
            name='intake_date',
            field=models.DateField(default='12/14/2023'),
        ),
    ]
