# Generated by Django 5.0 on 2023-12-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_cat_is_adopted_alter_cat_intake_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrecord',
            name='adopter_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adoptionrecord',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adoptionrecord',
            name='contact_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='adoptionrecord',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptionrecord',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='adoptionrecord',
            name='street_address',
            field=models.CharField(max_length=50),
        ),
    ]
