# Generated by Django 5.0 on 2023-12-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_adoptionrecord_adopter_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spayneuterrecord',
            name='clinic_city',
        ),
        migrations.RemoveField(
            model_name='spayneuterrecord',
            name='clinic_name',
        ),
        migrations.RemoveField(
            model_name='spayneuterrecord',
            name='clinic_postal_code',
        ),
        migrations.RemoveField(
            model_name='spayneuterrecord',
            name='clinic_state',
        ),
        migrations.RemoveField(
            model_name='spayneuterrecord',
            name='clinic_street_address',
        ),
    ]
