# Generated by Django 5.0 on 2023-12-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_cat_intake_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrecord',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
    ]
