# Generated by Django 5.0 on 2023-12-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_adoptionrecord_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='health_records',
        ),
        migrations.RemoveField(
            model_name='adoptionrecord',
            name='adoption_complete',
        ),
        migrations.DeleteModel(
            name='HealthRecord',
        ),
    ]
