# Generated by Django 5.0 on 2023-12-15 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_remove_cat_health_records_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='vaccinations',
        ),
        migrations.AlterField(
            model_name='spayneuterrecord',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.cat'),
        ),
    ]
