# Generated by Django 5.0 on 2023-12-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCat',
            fields=[
                ('cat_ID', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(default='Uknown', max_length=30)),
                ('intake_date', models.DateField(default='12/06/2023')),
                ('is_neutered', models.BooleanField(verbose_name='Spayed or Neutered')),
            ],
        ),
    ]
