# Generated by Django 5.0 on 2023-12-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catentry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('a', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='createcat',
            name='is_neutered',
        ),
        migrations.AddField(
            model_name='createcat',
            name='cat_sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='createcat',
            name='cat_surgery_status',
            field=models.CharField(choices=[('Spayed', 'Spayed'), ('Neutered', 'Neutered'), ('Unknown', 'Unknown status'), ('Needs Surgery', 'Needs Surgery')], default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='createcat',
            name='cat_ID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='createcat',
            name='cat_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='createcat',
            name='intake_date',
            field=models.DateField(default='2023-12-06'),
        ),
    ]
