# Generated by Django 5.0 on 2023-12-06 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catentry', '0002_a_remove_createcat_is_neutered_createcat_cat_sex_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
    ]
