# Generated by Django 5.0 on 2023-12-07 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catentry', '0003_delete_a'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateCat',
            new_name='Cat',
        ),
    ]
