# Generated by Django 5.0 on 2023-12-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catentry', '0004_rename_createcat_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='cat_status',
            field=models.CharField(choices=[('UA', 'Unavailable'), ('AS', 'Available Soon'), ('AN', 'Ready for Adoption'), ('AD', 'Adopted')], default='UA', max_length=2),
        ),
    ]
