# Generated by Django 5.0 on 2023-12-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catentry', '0005_cat_cat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='photo',
            field=models.ImageField(default='None', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('UK', 'Unknown')], default='UK', max_length=2),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_status',
            field=models.CharField(choices=[('UA', 'Unavailable'), ('AS', 'Available Soon'), ('AN', 'Ready for Adoption'), ('AD', 'Adopted'), ('UK', 'Unknown Adoption Status')], default='UK', max_length=2),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_surgery_status',
            field=models.CharField(choices=[('S', 'Spayed'), ('N', 'Neutered'), ('UK', 'Unknown Surgery Status'), ('NEED', 'Needs Surgery')], default='UK', max_length=4),
        ),
    ]
