# Generated by Django 5.0 on 2023-12-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catentry', '0006_cat_photo_alter_cat_cat_name_alter_cat_cat_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_status',
            field=models.CharField(choices=[('Unavailable', 'Unavailable'), ('Available Soon', 'Available Soon'), ('Available Now', 'Ready for Adoption'), ('Adopted', 'Adopted'), ('Unknown Adoption Status', 'Unknown Adoption Status')], default='Unknown Adoption Status', max_length=30),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_surgery_status',
            field=models.CharField(choices=[('Spayed', 'Spayed'), ('Neutered', 'Neutered'), ('Uknown Surgery Status', 'Unknown Surgery Status'), ('Needs Surgery', 'Needs Surgery')], default='Uknown Surgery Status', max_length=25),
        ),
        migrations.AlterField(
            model_name='cat',
            name='intake_date',
            field=models.DateField(default='2023-12-07'),
        ),
    ]
