# Generated by Django 5.0 on 2023-12-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catentry', '0007_alter_cat_cat_sex_alter_cat_cat_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='adoption_date',
            field=models.DateField(default='2023-12-07'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_status',
            field=models.CharField(choices=[('Unavailable', 'Unavailable'), ('Available Soon', 'Available Soon'), ('Available Now', 'Available Now'), ('Adopted', 'Adopted'), ('Unknown Adoption Status', 'Unknown Adoption Status')], default='Unknown Adoption Status', max_length=30),
        ),
    ]
