# Generated by Django 5.0 on 2023-12-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catentry', '0008_cat_adoption_date_alter_cat_cat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='adoption_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
