# Generated by Django 5.0 on 2023-12-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catentry', '0011_alter_adopter_adopter_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='adopter_city',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='adopter_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='adopter_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='adopter_state',
            field=models.TextField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='adopter_street_address',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='adopter_zip',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
